### ISSUE TITLE
Mixin Application Error

### ISSUE THREAD

**Issue by Siuolplex** [Shnupbups/Piglib#1] opened 2020-12-11 16:01 UTC
Note: I am reporting this on one of my player's behalf. 

Bug: PiglinBrainMixin errors out with an application error when opening a chest. The user seemed to be on a snapshot, so I can understand if your unable to support it.

https://gist.github.com/Siuolthepic/0f326c6c4519cb24c9be2f329aaf8764

More info: The player was in the overworld when this crash happened.

**Comment by Shnupbups** [comment] 2020-12-12 00:37
Definitely caused by being on a snapshot, will release a version that works on snapshots soon.

**Comment by Shnupbups** [comment] 2020-12-13 10:44
Fixed in 1.0.2-1.17-snapshot

**Closed as completed by Shnupbups** 2020-12-13 10:44 UTC

**Comment by Siuolplex** [comment] 2020-12-14 00:10
Alright, thank you! Ill push an update out for my mod with support for that in the JIJ'ed version!
